export default {
  categories: [
    "Music",
    "Arts",
    "Food & Drink",
    "Film & Media",
    "Sports & Fitness",
    "Spirituality",
    "Health",
    "Science & Tech",
    "Business",
    "Community",
    "Travel & Outdoor",
    "Charity & Causes",
    "Family & Education",
    "School Activities",
    "Holiday",
    "Government",
    "Fashion",
    "Home & Lifestyle",
    "Auto, Boat, Air",
    "Hobbies",
    "Other",
  ],
  types: [
    "Conference",
    "Expo",
    "Seminar",
    "Retreat",
    "Class",
    "Party",
    "Festival",
    "Tour",
    "Convention",
    "Performance",
    "Screening",
    "Gala",
    "Networking",
    "Rally",
    "Tournament",
    "Game",
    "Race",
    "Attraction",
    "Other",
  ],
};
